version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: development.Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 9229:9229