version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: production.Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_HOST=redis
      - CACHE_EXPIRE_TIME=10000
      - CACHE_CAPACITY=10
    ports:
      - 3000:3000

  redis:
    image: redis:alpine